# Generated by Django 6.0.1 on 2026-02-20 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("height", models.FloatField(help_text="cm")),
                ("weight", models.FloatField(help_text="kg")),
                ("target_weight", models.FloatField(blank=True, null=True)),
                ("job_type", models.CharField(max_length=50)),
                (
                    "work_nature",
                    models.CharField(
                        choices=[
                            ("desk", "Desk"),
                            ("field", "Field"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stress_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sleep_hours", models.FloatField()),
                (
                    "personality",
                    models.CharField(
                        choices=[
                            ("introvert", "Introvert"),
                            ("extrovert", "Extrovert"),
                            ("ambivert", "Ambivert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "smoking",
                    models.CharField(
                        blank=True,
                        choices=[("", "Choose"), ("yes", "Yes"), ("no", "No")],
                        max_length=10,
                    ),
                ),
                (
                    "alcohol",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("occasional", "Occasional"),
                            ("regular", "Regular"),
                        ],
                        max_length=20,
                    ),
                ),
                ("water_intake", models.FloatField(help_text="Liters per day")),
                (
                    "food_preference",
                    models.CharField(
                        choices=[
                            ("veg", "Vegetarian"),
                            ("nonveg", "Non-Vegetarian"),
                            ("vegan", "Vegan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meals_per_day", models.IntegerField()),
                ("allergies", models.TextField(blank=True)),
                ("medical_conditions", models.TextField(blank=True)),
                (
                    "health_goal",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("weight_gain", "Weight Gain"),
                            ("muscle_gain", "Muscle Gain"),
                            ("general", "General Health"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="userregistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("ph_no", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FoodRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("immunity", "Immunity Boost"),
                            ("general", "General Health"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("juice", "Juice"),
                            ("light", "Light Food"),
                            ("heavy", "Heavy Food"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "diet_type",
                    models.CharField(
                        choices=[("veg", "Vegetarian"), ("nonveg", "Non-Vegetarian")],
                        max_length=20,
                    ),
                ),
                ("recommendation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("duration_days", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("diet_followed", models.BooleanField(default=False)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.trackingplan",
                    ),
                ),
            ],
            options={
                "unique_together": {("plan", "date")},
            },
        ),
    ]
