# Generated by Django 5.2.9 on 2026-03-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingplan",
            name="reset_count",
            field=models.IntegerField(default=0),
        ),
    ]
